app/elective/admin/models.py
class SignupDate(object):

    def __init__(self, id, grade_lvl, start, end, course_year, tri_nbr):
        self.id = id

        self.grade_lvl = grade_lvl

        self.start = start

        self.end = end

        self.course_year = course_year

        self.tri_nbr = tri_nbr

    def __str__(self):
        return "\n%s, %s, %s, %s, %s, %s" % (self.id, self.grade_lvl, self.start, self.end, self.course_year, self.tri_nbr)

app/elective/__init__.py
from app.shared.models import NestableBlueprint

elective_mod = NestableBlueprint('elective', __name__, url_prefix='/elective_enroll')

import app.elective.views

from admin import admin_mod
from teacher import teacher_mod
from student import student_mod

elective_mod.register_blueprint(admin_mod)
elective_mod.register_blueprint(teacher_mod)
elective_mod.register_blueprint(student_mod)

app/elective/admin/__init__.py
from flask import Blueprint

admin_mod = Blueprint('elective_admin', __name__, url_prefix='/admin')

import app.elective.admin.views

app/elective/admin/controllers.py
from app.db import DB, insert, insertmany, query_one, query, delete, update

from app.elective.admin.models import *

from datetime import datetime

# Updates the enroll date for an elective
def update_enroll_date(grade_lvl, tri_nbr, course_year, start, end):

    update(DB.ELECTIVE, "UPDATE sigup_dates SET tri_nbr=%s, course_year=%s, start=%s, end=%s, trimester "
                        "WHERE grade_lvl=%s", [tri_nbr, course_year, start, end, grade_lvl], True)

def get_signup_dates():
    signup_dates = []
    results = query(DB.ELECTIVE, "SELECT * FROM signup_dates")

    for result in results:
        signup_dates.append(SignupDate(result[0], result[1], result[2], result[3], result[4], result[5]))

    return signup_dates

app/elective/admin/views.py
from app.elective.admin import admin_mod

from app.shared.controllers import requires_token
from app.elective.teacher.controllers import get_electives
from app.elective.admin.controllers import get_signup_dates, update_enroll_date

from flask import g, redirect, url_for, render_template, request, jsonify, make_response


@admin_mod.before_request
@requires_token
def check_teacher():
    if g.user.get_role('ELEN') != 'ADM':
        return redirect(url_for('elective'))

# TODO: Make admin route a way to update trimester/elective enroll opening/closings
# Admins should be able to look up 
@admin_mod.route('/')
def index():
    return render_template("./elective/admin/index.html", electives=get_electives())

@admin_mod.route('/signup_dates')
def signup_dates():
    return render_template("./elective/admin/signup_dates.html", dates=get_signup_dates())

@admin_mod.route('/signup_dates', methods=['PUT'])
def update_dates():
    data = request.get_json(force=True, silent=True)

    grades = data['grades']

    if len(grades) > 0:

        for grade in grades:

            grade_lvl = grade
            tri_nbr = grades[grade]['tri_nbr']
            course_year = grades[grade]['course_year']
            start = grades[grade]['start']
            end = grades[grade]['end']

            update_enroll_date(grade_lvl, tri_nbr, course_year, start, end)

        return make_response(jsonify({'Info': 'Successfully updated.'}), 200)
    else:
        return make_response(jsonify({'Info': 'Missing parameters!'}), 401)

app/elective/student/__init__.py
from flask import Blueprint

student_mod = Blueprint('elective_student', __name__, url_prefix='/student')

import app.elective.student.views

app/elective/student/controllers.py
from app.db import DB, insert, insertmany, query_one, query, delete, update

from app.elective.student.models import ElectiveSection, Elective, ElectiveTeacher, EnrollmentTime

from config import Config
from util import datetime_from_string, us_format

from datetime import datetime

# Make Query to DB to check whether enrollment is open for grade level
def get_enrollment_time(grade_level):
    result = query_one(DB.ELECTIVE, "SELECT grade_lvl, start, end, course_year, tri_nbr "
                                  "FROM signup_dates t "
                                  "WHERE t.grade_lvl = %s "
                                  "AND NOW() >= t.start "
                                  "AND NOW() < t.end", [grade_level])

    if result:

        start_time = result[1]
        end_time = result[2]

        return EnrollmentTime(result[0], start_time, end_time, result[3], result[4])
    else:
        return EnrollmentTime(grade_level, None, None, get_current_year(), '-1')

def enrollment_open(grade_level):
    result = query_one(DB.ELECTIVE, "SELECT * "
                                  "FROM signup_dates t "
                                  "WHERE t.grade_lvl = %s "
                                  "AND NOW() >= t.start "
                                  "AND NOW() <= t.end", [grade_level])

    return (not result is None)

# Enroll a user in an elective section
def enroll_user(usr_id, section_id):
    print(usr_id, section_id)
    insert(DB.ELECTIVE, 'INSERT INTO elective_user_xref (section_id, usr_id) VALUES (%s, %s) '
                        'ON DUPLICATE KEY UPDATE section_id=section_id', [section_id, usr_id])

# Remove a user from an elective_section
def drop_section(usr_id, section_id):
    delete(DB.ELECTIVE, 'DELETE FROM elective_user_xref WHERE usr_id=%s AND section_id=%s', [usr_id, section_id])

# Returns whether an elective
def is_section_full(section_id):

    section_info = query_one(DB.ELECTIVE, "SELECT enrolled_count, max "
                                     "FROM elective_section "
                                     "WHERE section_id = %s", section_id)

    return section_info[0] >= section_info[1]

def get_enrolled_sections(usr_id, year, tri):

    sections = query(DB.ELECTIVE, 'SELECT section.section_id, section.elective_id, e.name, e.desc, e.prereq, section.room_nbr, section.max, section.enrolled_count, section.section_nbr, t.usr_id, t.usr_first_name, t.usr_last_name '
                                  'FROM elective_section section, elective e, user t '
                                  'WHERE e.elective_id = section.elective_id '
                                  'AND section.course_year = %s '
                                  'AND section.tri = %s '
                                  'AND section.section_id in (SELECT section_id FROM elective_user_xref WHERE usr_id=%s) '
                                  'AND t.usr_id = section.teacher_id ORDER BY e.name', [str(year), int(tri), usr_id])

    e_sections = []

    for section in sections:
        elective_id = section[1]
        elective_name = section[2]
        elective_desc = section[3]
        elective_prereq = section[4]

        section_id = section[0]
        section_room_nbr = section[5]
        section_max = section[6]
        section_enrolled = section[7]
        section_nbr = section[8]

        teacher_id = section[9]
        teacher_first_name = section[10]
        teacher_last_name = section[11]

        elective = Elective(elective_id, elective_name, elective_desc, elective_prereq)
        teacher = ElectiveTeacher(teacher_id, teacher_first_name, teacher_last_name)
        times = get_times(section_id)

        e_sections.append(ElectiveSection(section_id, elective, section_nbr, tri, year, section_enrolled, section_max,
                                          section_room_nbr, teacher, times, False))

    return e_sections

# Get all sections available for a user
def get_sections(user_id, year, tri):
    sections = []

    if year != -1 and tri != -1 and not Config.DEBUG:

        sections = query(DB.ELECTIVE,
                         'SELECT section.section_id, section.elective_id, e.name, e.desc, e.prereq, section.room_nbr, section.enrolled_count, section.section_nbr, section.max, t.usr_id, t.usr_first_name, t.usr_last_name '
                         'FROM elective_section section, elective e, user t '
                         'WHERE course_year = %s '
                         'AND tri = %s '
                         'AND e.elective_id = section.elective_id '
                         'AND section.enrolled_count < section.max '
                         'AND t.usr_id = section.teacher_id '
                         'AND NOT (section.section_id in (SELECT section_id FROM elective_user_xref WHERE usr_id=%s)) '
                         'ORDER BY e.name', [year, tri, user_id])

    else:

        sections = query(DB.ELECTIVE,
                         'SELECT section.section_id, section.elective_id, e.name, e.desc, e.prereq, section.room_nbr, section.enrolled_count, section.section_nbr, section.max, t.usr_id, t.usr_first_name, t.usr_last_name '
                         'FROM elective_section section, elective e, user t '
                         'WHERE e.elective_id = section.elective_id '
                         'AND t.usr_id = section.teacher_id '
                         'AND NOT (section.section_id in (SELECT section_id FROM elective_user_xref WHERE usr_id=%s)) '
                         'ORDER BY e.name', [user_id])

    e_sections = []

    for section in sections:

        elective_id = section[1]
        elective_name = section[2]
        elective_desc = section[3]
        elective_prereq = section[4]

        section_id = section[0]
        section_room_nbr = section[5]
        section_enrolled = section[6]
        section_nbr = section[7]
        section_max = section[8]

        teacher_id = section[9]
        teacher_first_name = section[10]
        teacher_last_name = section[11]

        elective = Elective(elective_id, elective_name, elective_desc, elective_prereq)
        teacher = ElectiveTeacher(teacher_id, teacher_first_name, teacher_last_name)
        times = get_times(section_id)

        s = ElectiveSection(section_id, elective, section_nbr, tri, year, section_enrolled, section_max,
                            section_room_nbr, teacher, times, False)

        s.teacher = teacher

        e_sections.append(s)

    return e_sections

# Get all current elective sections for a tri/year
def get_all_sections(year, tri):

    sections = query(DB.ELECTIVE, 'SELECT section.section_id, section.elective_id, e.name, e.desc, e.prereq, section.room_nbr, section.enrolled_count, section.section_nbr, section.max, t.usr_id, t.usr_first_name, t.usr_last_name '
                                      'FROM elective_section section, elective e, user t '
                                      'WHERE e.elective_id = section.elective_id '
                                      'AND t.usr_id = section.teacher_id ')

    e_sections = []

    for section in sections:
        print(section)

        elective_id = section[1]
        elective_name = section[2]
        elective_desc = section[3]
        elective_prereq = section[4]

        section_id = section[0]
        section_room_nbr = section[5]
        section_enrolled = section[6]
        section_nbr = section[7]
        section_max = section[8]

        teacher_id = section[9]
        teacher_first_name = section[10]
        teacher_last_name = section[11]


        elective = Elective(elective_id, elective_name, elective_desc, elective_prereq)
        teacher = ElectiveTeacher(teacher_id, teacher_first_name, teacher_last_name)
        times = get_times(section_id)

        s = ElectiveSection(section_id, elective, section_nbr, tri, year, section_enrolled, section_max,
                        section_room_nbr, teacher, times, False)

        s.teacher = teacher

        e_sections.append(s)

    return e_sections

# Returns the current school year formatted in "YEAR-END_YEAR" form
def get_current_year():
    return '%d-%s' % (datetime.utcnow().year, str(datetime.utcnow().year + 1)[2:])

# Temporary solution for getting the corresponding times for a section
def get_times(section_id):
    result = query(DB.ELECTIVE, "SELECT time_short_desc "
                                   "FROM elective_time time, elective_section_time_xref x "
                                   "WHERE x.section_id = %s "
                                   "AND time.time_id = x.time_id", [section_id])
    times = []

    for time in result:
        times.append(time[0])

    return times

# Returns the current '%d-%d' year string and trimester
def get_current_info():
    current_year = get_current_year()

    formatted_year = str(current_year.split('-')[0])

    print(formatted_year)

    # ps_year format - Ex: 2018 = 28
    formatted_year = formatted_year[0] + formatted_year[-1]

    current_tri = query_one(DB.ELECTIVE, 'SELECT tri_nbr FROM atcsdevb_dev_shared.trimester ' +
                                         'WHERE NOW() <= end_dt ' +
                                         'AND NOW() >= start_dt ' +
    #                                    'AND ps_year = %s ' +
                                         'ORDER BY end_dt')[0]
    return [current_year, current_tri]

def get_amount_left(section_id):
    section_info = query_one(DB.ELECTIVE, "SELECT es.max - es.enrolled_count "
                                          "FROM elective_section es "
                                          "WHERE section_id = %d", [section_id])[0]

    return section_info

app/elective/student/views.py
from app.elective.student import student_mod

from app.shared.controllers import requires_token
from app.elective.student.controllers import *

from flask import g, redirect, url_for, render_template, request, jsonify

# Explanation:
# This file is a sub app for the elective enroll application
# It is specified for students
# Only students can view these pages
# The First Route Below makes sure that the requester of this app, student_mod, is a student
# If not, the user is redirected to the index page of the 'elective' app itself
# The name of this app is elective_student
# Every individual app on flask has its own name
# Its sub apps have the name '%PRIMARY_APP_NAME%_%SUB_APP_NAME%'
# These names are useful because they can be used to get urls of routes
# For example, url_for('elective.index') would return the route with the function named index

# Checks whether the requester
@student_mod.before_request
@requires_token
def check_teacher():
    if g.user.get_role('ELEN') != 'STD':
        return redirect(url_for('elective'))

# pages

# A route for the student_mod app
@student_mod.route('/')
def index():
    enroll_info = get_enrollment_time(g.user.get_grade_level())

    enrolled_sections = []
    available_sections = []

    if not enroll_info.start_time is None:

        enrolled_sections = get_enrolled_sections(g.user.get_id(), enroll_info.course_year, enroll_info.tri_nbr)
        available_sections = get_sections(g.user.get_id(), enroll_info.course_year, enroll_info.tri_nbr)

    return render_template("elective/student/index.html", sections=available_sections, enroll_info=enroll_info, enrolled_sections=enrolled_sections)

@student_mod.route('/enroll/<int:id>', methods=['PUT'])
def enroll(id):
    data = request.get_json(force=True, silent=True)

    section_id = id
    usr_id = data['usr_id']
    will_enroll = data['enroll']

    if enrollment_open(g.user.get_grade_level()):
        if will_enroll:
            if not is_section_full(section_id):
                enroll_user(usr_id, section_id)

                return jsonify({"has_enrolled": True, "Error": None})

            else:
                return jsonify({"has_enrolled": False, "Error": "Elective Section Full."})
        else:
            drop_section(usr_id, section_id)
            return jsonify({"has_enrolled": False, "Error": None})

    else:
        return jsonify({"has_enrolled": False, "Error": "Enrollment Not Open"})


@student_mod.route('/enroll/update', methods=['PUT'])
def ping():
    data = request.get_json(force=True, silent=True)

    section_ids = data['section_ids']

    if(section_ids):

        amount_left = {}

        for i in range(len(section_ids)):
            amount_left[section_ids[i]] = get_amount_left(section_ids[i])

        return jsonify(amount_left)

    else:
        return jsonify({"Error": "Invalid parameters"})

app/elective/teacher/__init__.py
from flask import Blueprint

teacher_mod = Blueprint('elective_teacher', __name__, url_prefix='/teacher')

import app.elective.teacher.views

app/elective/views.py
from app.elective import elective_mod

from app.shared.controllers import requires_token

from flask import g, redirect, url_for


@elective_mod.before_request
@requires_token
def check_auth():
    print("checking token....")

@elective_mod.route('/')
def index():
    type_code = g.user.get_role('ELEN')

    if type_code == 'STD':
        return redirect(url_for('elective_student.index'))
    elif type_code == 'TCH':
        return redirect(url_for('elective_teacher.index'))
    elif type_code == 'ADM':
        return redirect(url_for('elective_admin.index'))
    else:
        return redirect('/')

app/templates/elective/admin/index.html
{% extends "base.html" %}

{% block styles %}
    {{ super() }}

    <link rel="stylesheet" href="{{ url_for('static', filename='css/elective/admin/main.css') }}">
{% endblock %}


{% block content %}

    <div class="container">
    <h3 class="center-align">Admin Tools</h3>
    <ul class="collection with-header">

        <a href="mimic_user" class="collection-item avatar">
            <i class="material-icons circle red">person</i>
            <h6 class="title">Mimic User</h6>
            <p class="small-text">Log in as any user in the database and use the app as if you were them.</p>
        </a>

        <a href="audit_viewer" class="collection-item avatar">
            <i class="material-icons circle red">edit</i>
            <h6 class="title">Audit Viewer</h6>
            <p class="small-text">View all database audits from the past week.</p>
        </a>

        <a href="log_viewer" class="collection-item avatar">
            <i class="material-icons circle red">report_problem</i>
            <h6 class="title">Log Viewer</h6>
            <p class="small-text">View the application log.</p>
        </a>

        <a href="signup_dates" class="collection-item avatar">
            <i class="material-icons circle red">access_time</i>
            <h6 class="title">Signup Dates</h6>
            <p class="small-text">View and edit signup deadlines by grade.</p>
        </a>

        <a href="roles" class="collection-item avatar">
            <i class="material-icons circle red">person_add</i>
            <h6 class="title">Roles</h6>
            <p class="small-text">Set and manage roles for projects.</p>
        </a>

        <a href="variables" class="collection-item avatar">
            <i class="material-icons circle red">view_quilt</i>
            <h6 class="title">Variables</h6>
            <p class="small-text">Set and manage variables for projects.</p>
        </a>


        <!--<a href="roles" class="collection-item avatar">
            <i class="material-icons circle red">person_add</i>
            <h6 class="title">Roles</h6>
            <p class="small-text">Set roles for proctoring.</p>
        </a>-->
    </ul>
</div>

{% endblock %}

app/templates/elective/admin/signup_dates.html
{% extends "base.html" %}

{% block styles %}
    {{ super() }}

    <link rel="stylesheet" href="{{ url_for('static', filename='css/elective/admin/main.css') }}">
{% endblock %}


{% block content %}
<div class="container" style="text-align:center; width:90%; margin: 0 25px;">
    <h3>Signup Dates</h3>
</div>

<table class="highlight" style="text-align: center; width: 80%;  margin-left: auto; margin-right: auto;">
    <thead>
    <tr>
        <th>Grade Level</th>
        <th>Course Year</th>
        <th>Trimester</th>
        <th>Start Date</th>
        <th>End Date</th>
    </tr>
    </thead>

    <tbody>
        {% for date in dates %}

            <tr>
                <input type="hidden" name="hdGrade[]" value="{{ date.grade_lvl }}">

                <td style="text-align: center">{{ date.grade_lvl }}</td>
                <td class="small_column">
                    <div class="input-field col s6">
                        <input type="text" class="course_year" name="course_year[]" value="{{ date.course_year }}">
                    </div>
                </td>
                <td class="small_column">
                    <div class="input-field col s6">
                        <input type="text" class="tri_nbr" name="tri_nbr[]" value="{{ date.tri_nbr }}">
                    </div>
                </td>
                <td class="small_column">
                    <div class="input-field col s6">
                        <input type="text" class="start_date" name="start_date[]" value="{{ date.start }}">
                    </div>
                </td>
                <td class="small_column">
                    <div class="input-field col s6">
                        <input type="text" class="end_date" name="end_date[]" value="{{ date.end }}">
                    </div>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<div class="row" style="text-align:center; margin-bottom: 50px;">
    <button style="cursor: pointer" class="waves-effect waves-light btn" id="submit"
            value="Update Dates">
        Submit
    </button>
    <a id="return_home" style="cursor: pointer; text-decoration: none;" class="waves-effect waves-light btn" type="submit" name="choice"
            value="Back" href="{{ url_for('elective_admin.index') }}">
        Cancel
    </a>
</div>

<script type="text/javascript">

    $(document).ready(function() {

        $("#submit").click(function() {

            $("#submit").addClass("disable");

            let grades = {9: {}, 10: {}, 11: {}, 12: {}};

            let gr = 9;

            for(course in $(".course_year")) {
                grades[gr].course_year = course.val();
                gr++;
            }

            gr = 9;

            for(tri_nbr in $(".tri_nbr")) {
                grades[gr].tri_nbr = tri_nbr.val();
                gr++;
            }

            gr = 9;

            for(start in $(".start_date")) {
                grades[gr].start = start.val();
                gr++;
            }

            gr = 9;

            for(end in $(".end_date")) {
                grades[gr].end = end.val();
                gr++;
            }

            $.ajax('{{ url_for('elective_admin.update_dates') }}',
                {
                    method: 'PUT',

                })
        });


    });

</script>

{% endblock %}